name: Build module

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install coreutils binutils curl fastjar

    - name: Checkout source
      uses: actions/checkout@v3
      with:
        repository: 9Omori/patch-up_param
        ref: main
        path: ~
    
    - name: Gather files
      run: |
        cd ~/module
        mkdir -p META-INF/com/google/android
        curl -L https://github.com/topjohnwu/Magisk/raw/master/scripts/module_installer.sh -o ./META-INF/com/google/android/update-binary
        echo "#MAGISK" > updater-script

    - name: Package module
      run: |
        cd ~/module
        fastjar patch-up_param.zip *
      
    - name: Upload final output
      uses: actions/upload-artifact@v3
      with:
        path: ~/module/patch-up_param.zip
