name: Make module

on:
  push:
    paths:
      - 'module/customize.sh'
      - 'module/uninstall.sh'
      - 'module/module.prop'
      - 'update.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install coreutils binutils curl fastjar

    - name: Clone source
      run: |
        git clone https://github.com/9Omori/patch-up_param.git ~/patch-up_param

    - name: Make structure
      run: |
        cd ~/patch-up_param/module
        mkdir -pv META-INF/com/google/android

    - name: Gather files
      run: |
        cd ~/patch-up_param/module
        curl -Ls https://github.com/topjohnwu/Magisk/raw/master/scripts/module_installer.sh -o ./META-INF/com/google/android/update-binary
        echo "#MAGISK" >META-INF/com/google/android/updater-script

    - name: Package module
      run: |
        cd ~/patch-up_param/module
        fastjar -cf ~/patch-up_param.zip *
      
    - name: Upload final output
      uses: actions/upload-artifact@v3
      with:
        name: out
        path: |
          ~/patch-up_param.zip
