name: Build module

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
      with:
        repository: 9Omori/patch-up_param
        ref: main
        path: ~
    
    - name: Gather files
      run: |
        PATH="~/module/META-INF/com/google/android"
        [ -d "$PATH" ] || mkdir -p $PATH
        cd $PATH
        curl -L https://github.com/topjohnwu/Magisk/raw/master/scripts/module_installer.sh -o ./update-binary
        echo "#MAGISK" > updater-script
      
    - name: Upload final output
      uses: actions/upload-artifact@v3
      with:
        name: patch-up_param.zip
        path: |
          ~/module/customize.sh
          ~/module/META-INF/com/google/android/update-binary
          ~/module/META-INF/com/google/android/updater-script
          ~/module.prop
          ~/uninstall.sh
