name: Build module

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install coreutils binutils curl fastjar

    - name: Clone source
      run: |
        git clone https://github.com/9Omori/patch-up_param.git ~/patch-up_param

    - name: Gather files
      run: |
        cd ~/patch-up_param/module
        mkdir -p META-INF/com/google/android
        curl -L https://github.com/topjohnwu/Magisk/raw/master/scripts/module_installer.sh -o ./META-INF/com/google/android/update-binary
        echo "#MAGISK" > updater-script

    - name: Package module
      run: |
        cd ~/patch-up_param/module
        fastjar patch-up_param.zip *
        mv patch-up_param.zip ~
      
    - name: Upload final output
      uses: actions/upload-artifact@v3
      with:
        path: ~/patch-up_param.zip
